### ISSUE TITLE
Environment variables in content

### ISSUE THREAD

**Issue by srepollock** [tsickert/discord-webhook#100]
Hi there, I'm looking to use environment variables in the content string. It seems as though it's unsupported.

Wondering if this could be a new feature?

Something along the lines of:

```yaml
notify-success:
  runs-on: ubuntu-latest
  if: ${{ success() }}
  steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "Build Succeeded: ${{GITHUB_REF_NAME}} - ${{GITHUB_RUN_ID}}"
```

(These are [default environment variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) in GitHub Actions, so this is a valid job you can use to test right here).
