### ISSUE TITLE
Question: Wildcards on filename

### ISSUE THREAD

**Issue by Sylensky** [tsickert/discord-webhook#123]
Hello,

i was wondering if the filename property supports wildcard. My workflow would look something like this then:
```yml
...
 - name: Upload File
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          filename: my_awesome_folder/data/file_with_version_*.txt
...
```

Also i tested to pass multiple files with no success so far is that supported?
