### ISSUE TITLE
How to include a newline on the embed description?

### ISSUE THREAD

**Issue by faloi** [tsickert/discord-webhook#140]
Hi there, thanks for this handy action.

I've been unsuccessfully trying to add a new line, this is what I tried:

```yaml
embed-description: 'Ultimos cambios:\n_${{ github.event.head_commit.message }}_'
```

But sadly, the `\n` appears on the message: 

![image](https://user-images.githubusercontent.com/1585835/218850255-adae5d8e-f33e-4da7-bb47-3ec38b135847.png)

Any idea of how to achieve this?

**Comment by tsickert** [comment]
Glad it's helpful! 

I haven't confirmed this works, but you could this multiline yaml format with the `|`?

```yaml
  embed-description: |
    Ultimos cambios:
    ${{ github.event.head_commit.message }}
```

Hopefully the commit message will still interpolate with that format.
