### ISSUE TITLE
Missing 'sender', preventing usage

### ISSUE THREAD

**Issue by RhenaudTheLukark** [tsickert/discord-webhook#156]
Hey there, I tried using this project for sending a custom message whenever a given workflow is finished, but an error keeps appearing no matter what I do.

My current runs are triggered manually, through the `workflow_dispatch` event.

Here's the error: `{"sender": ["This field is required"]}`

And here's the file, although it may not bring much as I have a very basic usage of this library.

```yaml
name: Send a message to the channel cyf-nightly

on:
  workflow_run:
    workflows: ["Build CYF"]
    types:
      - completed
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_LINK }}
        content: "The last CYF nightly is ready to be used! Enjoy!"

**Comment by Larzous** [comment]
I can confirm I am also getting sender errors required with this.  I even attempted to add the sender via the script and it doesn't like it.

```yml
  jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          sender: $GITHUB_ACTOR
          content: Deploy -- Asset Manager
```
![image](https://github.com/tsickert/discord-webhook/assets/68357365/6129fb2f-e4d2-4826-966c-2279e13ed88e)
