### ISSUE TITLE
send to discord using embed - improve doc

### ISSUE THREAD

**Issue by boly38** [tsickert/discord-webhook#16]
Hi,

I like your project, thanks for this action.

I would like to improve `embed` doc:
- add a link to the discord official meaning of embed
- add some information about field limits (ex. description max length is 4096)
- add a sample of embed without using intermediate json file

example
```
      - name: Send my report to discord channel as embed
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "this is embed sample"
          embed-title: "embed title"
          embed-description: "embed description"
          embed-thumbnail-url: "https://www.google.com/search?q=discord+embed"

```
