### ISSUE TITLE
Encoding issue when sending files

### ISSUE THREAD

**Issue by linus-jansson** [tsickert/discord-webhook#177]
Hello, it seems like the workflow has some issues sending text files that includes `å,ä,ö`.

Even though I ensure that its utf8 encoding on the file the webhook still sends "vÃ¤xte" instead of "växte" in the output file. Can it be a encoding issue?
Here is the workflow that I wrote; 
```
name: Run main.ts

on:
  schedule:
    - cron: '0 8 * 1-3 *'
    - cron: '0 8 * 10-12 *'
    - cron: '0 7 * 3-10 *'
  push:
    branches:
      - main
jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build

    - name: Run main.ts
      env:
        API_BASE_URL: ${{ secrets.API_URL }}
      run: node dist/main.js > output.txt

    - name: Ensure UTF-8 encoding
      run: iconv -f utf-8 -t utf-8 output.txt > temp.txt && mv temp.txt output.txt

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: 'GitHub Actions'
        filename: output.txt
```
